Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,23 +1,27 @@
 version: 2.1
 
-#ommands:
-# destroy-environment:
-#   description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-#   parameters:
-#     # Add parameter here   
-#   steps:
-#     - run:
-#         name: Destroy environments
-#         when: on_fail
-#         command: |
-#           # Your code here
-#           exit 1
+commands:
+ destroy-environment:
+   description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+   parameters:
+     # Add parameter here 
+     workflow_id:
+        type: string 
+   steps:
+     - run:
+         name: Destroy environments
+         when: on_fail
+         command: |
+           # Your code here
+           aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
+           aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
+           exit 1
 
 # revert-migrations:
 #   description: Revert the last migration if successfully run in the current workflow.
-#   parameters:
+##   parameters:
 #     # Add parameter here     
-##  steps:
+#  steps:
 #     - run:
 #         name: Revert migrations
 #         # Add when this will run
@@ -143,39 +147,49 @@ jobs:
             npm audit --audit-level=critical
       
 
-#  deploy-infrastructure:
-#    docker:
-#      # Docker image here that supports AWS CLI
-#    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Ensure back-end infrastructure exists
-#          command: |
-#            aws cloudformation deploy \
-#              --template-file .circleci/files/backend.yml \
-#              #--tags project=your-tag \
-#              # --stack-name "your back-end stack name with workflow id" \
-#              # --parameter-overrides ID="your workflow id"  
-#              exit 1
-#      - run:
-#          name: Ensure front-end infrastructure exist
-#          command: |
-#            aws cloudformation deploy \
-#              --template-file .circleci/files/frontend.yml \
-#              #--tags project=your-tag \
-#              # --stack-name "your front-end stack name with workflow id" \
-#              # --parameter-overrides ID="your workflow id"  
-#              exit 1
-#      - run:
-#          name: Add back-end ip to ansible inventory
-#          command: |
-#            # Your code here
-#            exit 1
-#      - persist_to_workspace:
-#          root: ~/
-#          paths:
-#            - project/.circleci/ansible/inventory.txt
-#      # Here's where you will add some code to rollback on failure      
+  deploy-infrastructure:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"   
+              
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"   
+              
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            BACK_END_PUBLIC_IP=$(aws ec2 describe-instances \
+              --query "Reservations[*].Instances[*].PublicIpAddress" \
+              --output text)
+            echo "[web]" >> .circleci/ansible/inventory.txt              
+            echo "$BACK_END_PUBLIC_IP" >> .circleci/ansible/inventory.txt              
+            pwd
+            cat .circleci/ansible/inventory.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+
 
 #  configure-infrastructure:
 #    docker:
@@ -312,16 +326,16 @@ jobs:
 workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
+ #     - build-frontend
+ #     - build-backend
+ #     - test-frontend:
+ ##         requires: [build-frontend]
+ #     - test-backend:
+ #         requires: [build-backend]
+ #     - scan-backend:
+ #         requires: [build-backend]
+ #     - scan-frontend:
+ #         requires: [build-frontend]
 #      - deploy-infrastructure:
 #          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
 #          filters:
